<script src="<?= base_url ?>assets/js/jquery-3.4.1.min.js"></script>
<script src="<?= base_url ?>assets/js/bootstrap.min.js"></script>
<script src="<?= base_url ?>assets/js/estados.js"></script>
<script src="<?= base_url ?>assets/js/validarFormularios.js"></script>
<script src="<?= base_url ?>assets/js/comentarios.js"></script>
<script src="<?= base_url ?>assets/js/comentariosAjax.js"></script>
<script src="<?= base_url ?>assets/js/direccionesEliminar.js"></script>
<script src="<?= base_url ?>assets/js/agregarDirecciones.js"></script>
<script src="<?= base_url ?>assets/js/pedidosJS.js"></script>
<script src="<?= base_url ?>assets/js/agregarCategoria.js"></script>
<script src="<?= base_url ?>assets/js/productsJS.js"></script>